---
- name: Creating a new EC2 instance.
  hosts: localhost
  gather_facts: false

  vars:
    #VPC:

    #ec2:
    region: us-east-1
    instance_type: t2.micro
    ami: ami-083654bd07b5da81d
    keypair: dharmil-website202111
    subnet_id: "{{ subnet.subnet.id }}"
    group: "{{ grp.group_id }}"

  tasks: 

    - name: Create an ec2 instance
      ec2: 
        key_name: "{{ keypair }}"
        group_id: "{{ group }}" #Group ID
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        wait: true
        region: "{{ region }}"
        count: 1 #default
        count_tag:
          Name: Demo
        instance_tags:
          Name: webserver
        vpc_subnet_id: "{{ subnet_id }}"
        assign_public_ip: yes
        volumes:
          - device_name: /dev/sda1
            volume_size: 30
            volume_type: gp3
            delete_on_termination: yes
      register: ec2

    - debug: 
        var: ec2
        var: ec2.instance.public_ip #publicIP
    