---
- name: Creating a new Demo EC2 instance.
  hosts: localhost
  gather_facts: false

  vars:
    #VPC:

    #ec2:
    region: us-east-1
    instance_type: t3.micro
    ami: ami-083654bd07b5da81d
    keypair: aws_webserver_202111
    subnet_id: subnet-0e8d9845d

  tasks: 

    - name: Create a new VPC
      amazon.aws.ec2_vpc_net:
        name: Test-Website-Demo
        cidr_block: 10.10.0.0/16
        region: "{{ region }}"


    - name: Create ec2 key Pair  

    - name: Create an ec2 instance
      ec2: 
        key_name: "{{ keypair }}"
        group: webserver_group #Group name
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        wait: true
        region: "{{ region }}"
        count: 1 #default
        count_tag:
          Name: Demo
        instance_tags:
          Name: Demo
        vpc_subnet_id: "{{ subnet_id }}"
        assign_public_ip: yes
      register: ec2
    