---
- name: Createing Subnet and getting Subnet ID in return
  hosts: localhost

  vars: 
    region: us-east-1

  tasks: 
    #Creation of VPC
    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: Website_Projects
        cidr_block: 10.10.0.0/16
        region: "{{ region }}"
        dns_hostnames: yes
        dns_support: yes
        ipv6_cidr: no
      #register: vpc
      register: vpc_id


    #Creation of Subnet
    - name: Create Subnet
      amazon.aws.ec2_vpc_subnet:
        tags: 
          Name: webserver
        az: us-east-1b
        region: "{{ region }}"
        cidr: 10.10.10.0/24
        map_public: yes
        vpc_id: "{{ vpc_id.vpc.id }}"
      register: subnet
    
    #Creating Internet Gateway
    - name: Create IGW
      ec2_vpc_igw:
        vpc_id: "{{ vpc_id.vpc.id }}"
        region: "{{ region }}"
        state: present
        tags: 
          Name: Webserver IGW
      register: igw

    #Create route tables
    - name: Create route table
      ec2_vpc_route_table:
        vpc_id: "{{ vpc_id.vpc.id }}"
        region: "{{ region }}"
        subnets: "{{ subnet.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"


    - debug:
        #var: vpc
        var: vpc_id.vpc.id
        var: subnet
        var: igw
