---
- name: Createing Subnet and getting Subnet ID in return
  hosts: localhost

  vars: 
    region: us-east-1

  tasks: 
    #Creation of VPC
    - name: Create VPC
      amazon.aws.ec2_vpc_net:
        name: Website_Projects
        cidr_block: 10.10.0.0/16
        region: "{{ region }}"
        dns_hostnames: yes
        dns_support: yes
        ipv6_cidr: no
      #register: vpc
      register: vpc_id


    #Creation of Subnet
    - name: Create Subnet
      amazon.aws.ec2_vpc_subnet:
        tags: 
          name: webserver
        az: us-east-1b
        region: "{{ region }}"
        cidr: 10.10.10.0/24
        map_public: yes
        vpc_id: "{{ vpc_id.vpc.id }}"
      register: subnet
    


    - debug:
        #var: vpc
        var: vpc_id.vpc.id
        var: subnet
      
